spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssh
    username: root
    password: zxcv1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true